### ISSUE TITLE
Builder pathfinding doesn't account for destroyed walls or new walls

### ISSUE THREAD

**Issue by jeffomatic** [jeffanddom/manchester#36]
The builder pathfinding system uses map data rather than live entity data to generate its paths. Ideally, it should:

1. Use wall entities from the entity manager, not the map.
2. Account for borders of the map (currently, tiles beyond the map edge are still considered neighbors).
3. Update every frame during the `leaveHost` state (in addition to the `returnToHost` state), so that it accounts for new wall state on the way to the target.

**Comment by dominic** [comment]
#1 covered in https://github.com/jeffanddom/yolorts/commit/fcefa44835a3859adbd4324fef66f2693a56b6b9

**Comment by jeffomatic** [comment]
old issue
