### ISSUE TITLE
Builder causes temporary freeze when target is a wall

### ISSUE THREAD

**Issue by jeffomatic** [jeffanddom/manchester#37]
If the pathfinder target is unreachable (i.e., it is a wall), the pathfinder algorithm enters a maximum-length search, causing freezes in the game.

**Comment by dominic** [comment]
Now that we've added a max path length, rather than crash it just gets reallllly slow when trying to place inside a wall.

**Comment by jeffomatic** [comment]
Update description for new non-crash behavior

**Comment by jeffomatic** [comment]
old issue
